definitions:
  Project:
    type: object
    properties:
      id:
        type: ObjectId
      username:
        type: string
      email:
        type: string
      password:
        type: string
    required:
      - username
      - email
      - password